services:
  # app:
    # image: search-clothes:0.0.1
    # ports:
    #   - 3000:3001
    # volumes:
    #   - ./uploads:/app/uploads
  tensorflow_serving:
    image: restnet50_model:latest
    ports:
      - 5000:5001
    # volumes:
    #   - app/model/1/resnet50_model:/models/1/resnet50_model
    # command: |
    #   --model_name=your_model
    #   --model_base_path=/models/your_model
  